name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: |
          cd rent
          chmod +x gradlew
      - name: Vérifier les permissions de gradlew
        run: |
          cd rent
          ls -l gradlew
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Docker images
        run: |
          export SHELL=/bin/bash
          docker build -t rent .
          docker images