name: CI
on:
  push:
    branches:
      - main  # Modifier la branche si nécessaire
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        run: |
          cd rent
          export SHELL=/bin/bash
          chmod +x gradlew
          ./gradlew build
      - name: Docker images
        working-directory: rent
        run: |
          cd rent
          export SHELL=/bin/bash
          docker build -t rent .
          docker images




name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        working-directory: rent
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Docker images
        working-directory: rent
        run: |
          export SHELL=/bin/bash
          docker build -t rent .
          docker images