name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test
        working-directory: rent
        run: |
          export SHELL=/bin/bash
          chmod +x gradlew
          ./gradlew build
      - name: Docker images
        working-directory: rent
        run: |
          export SHELL=/bin/bash
          docker build -t rent .
          docker images